name       : musescore
version    : 2.1.0
release    : 14
source     :
    - https://github.com/musescore/MuseScore/archive/v2.1.0.tar.gz : 0581b8dd4e9bef51f863baf5b7f03b518f9784c79c0d92d6f0e33b180dd63c47
license    : GPL-2.0
component  : multimedia.audio
summary    : MuseScore is an open source and free music notation software
description: |
    MuseScore is an open source and free music notation software
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(libssl)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - lame-devel
rundeps    :
    - qt5-quickcontrols
build      : |
    %apply_patches
    %make PREFIX=/usr USE_SYSTEM_FREETYPE=ON
install    : |
    %make_install PREFIX=/usr UPDATE_CACHE=FALSE USE_SYSTEM_FREETYPE=ON
    cd $installdir; qml_cache
