name       : musescore
version    : 3.3.2
release    : 24
source     :
    - https://github.com/musescore/MuseScore/archive/v3.3.2.tar.gz : 34c856a32ed1d2e725866e63fa0cedda033bfef0a915e2f0b0d83b63a79b2ee4
license    : GPL-2.0-only
component  : multimedia.audio
summary    : MuseScore is an open source and free music notation software
description: |
    MuseScore is an open source and free music notation software
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(libssl)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - lame-devel
    - portmidi-devel
rundeps    :
    - qt5-quickcontrols
setup      : |
    %cmake -DUSE_SYSTEM_FREETYPE=ON \
           -DCMAKE_BUILD_TYPE=Release \
           -DBUILD_CRASH_REPORTER=OFF
build      : |
    %make lrelease
    %make
install    : |
    %make_install PREFIX=/usr UPDATE_CACHE=FALSE USE_SYSTEM_FREETYPE=ON
    %qml_cache
