name       : musescore
version    : 2.0.3
release    : 5
source     :
    - https://github.com/musescore/MuseScore/archive/v2.0.3.tar.gz : 66c613f27fcc07252e856a51ed1162a9921f3d11ac130260763e2178b7098b01
license    : GPL-2.0
component  : multimedia.audio
summary    : MuseScore is an open source and free music notation software
description: |
    MuseScore is an open source and free music notation software
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - lame-devel
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr UPDATE_CACHE=FALSE
