name       : musescore
version    : 3.6.2
release    : 30
source     :
    - https://github.com/musescore/MuseScore/archive/v3.6.2.tar.gz : c37acc6d7a316f04925265d2d22a35d715888580e16eff846e9b621954133c45
license    : GPL-2.0-only
component  : multimedia.audio
summary    : MuseScore is an open source and free music notation software
description: |
    MuseScore is an open source and free music notation software
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(libssl)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - lame-devel
    - portmidi-devel
rundeps    :
    - qt5-quickcontrols2
setup      : |
    %cmake -DUSE_SYSTEM_FREETYPE=ON \
           -DCMAKE_BUILD_TYPE=Release \
           -DBUILD_CRASH_REPORTER=OFF
build      : |
    %make lrelease
    %make
install    : |
    %make_install PREFIX=/usr UPDATE_CACHE=FALSE USE_SYSTEM_FREETYPE=ON
    %qml_cache
