name       : musescore
version    : '3.0'
release    : 19
source     :
    - https://github.com/musescore/MuseScore/archive/v3.0.tar.gz : 678143411342bc7290364f7e7eeaba33ad9391b35cf3b6038861f0691a642d0e
license    : GPL-2.0-only
component  : multimedia.audio
summary    : MuseScore is an open source and free music notation software
description: |
    MuseScore is an open source and free music notation software
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(libssl)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - extra-cmake-modules
    - lame-devel
    - portmidi-devel
rundeps    :
    - qt5-quickcontrols
setup      : |
    %apply_patches
    %cmake -DUSE_SYSTEM_FREETYPE=ON
build      : |
    %make lrelease
    %make
install    : |
    %make_install PREFIX=/usr UPDATE_CACHE=FALSE USE_SYSTEM_FREETYPE=ON
    %qml_cache
