name       : musescore
version    : 4.0.2
release    : 31
source     :
    - https://github.com/musescore/MuseScore/archive/v4.0.2.tar.gz : 9907b75e6194405bf8c8d23d2bb1b03343c76258426a8aee11d161390fc4f06d
license    : GPL-3.0-only
component  : multimedia.audio
summary    : MuseScore is an open source and free music notation software
description: |
    MuseScore is an open source and free music notation software
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5NetworkAuth)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5QuickTemplates2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(libssl)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(xcb)
    - extra-cmake-modules
    - git
    - lame-devel
    - portmidi-devel
rundeps    :
    - qt5-graphicaleffects
    - qt5-quickcontrols
    - qt5-quickcontrols2
setup      : |
    %cmake -DUSE_SYSTEM_FREETYPE=ON \
           -DCMAKE_BUILD_TYPE=Release \
           -DMUSESCORE_BUILD_CONFIG=release \
           -DBUILD_CRASHPAD_CLIENT=OFF \
           -DBUILD_UNIT_TESTS=OFF \
           -DPACKAGE_FILE_ASSOCIATION=ON
build      : |
    %make lrelease
    %make
install    : |
    %make_install PREFIX=/usr UPDATE_CACHE=FALSE USE_SYSTEM_FREETYPE=ON BUILD_CRASHPAD_CLIENT=OFF
    %qml_cache

    # Remove empty directory
    rm -rvf $installdir/usr/share/mscore-4.0/locale/CMakeFiles

    # Remove unnecessary headers
    rm -rvf $installdir/usr/include

    # Remove unneccesary cmake artifacts
    rm -rvf $installdir/usr/lib64
